global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: 'jenkins'
    metrics_path: '/prometheus/'
    scheme: http
    static_configs:
        - targets: ['192.168.0.101:8080']

remote_write:
  - url: "http://192.168.0.101:3000/"
    basic_auth:
      username: "admin"
      password: "12345"
      # username: "prometheus"
      # password: "eyJrIjoiQlpYcjNIS0ttOFNOQ1FsMkJSYmVRZkZIOWQ3akZyVDkiLCJuIjoicHJvbWV0aGV1cyIsImlkIjoxfQ=="