version: "3.9"
    
services:
  mysql:
    image: mmmakarets-mysql:1.0.4
    container_name: mysql
    volumes:
      - ${VOLUME_DIR}/mysql:/var/lib/mysql
    restart: always
    
  wordpress:
    depends_on:
      - mysql
    image: mmmakarets-wordpress:1.0.5
    container_name: wordpress
    volumes:
      - ${VOLUME_DIR}/html:/var/www/html
    ports:
      - "80:80"
    restart: always
